/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Pixy2SpiJNI */
 
#ifndef _Included_Pixy2SpiJNI
#define _Included_Pixy2SpiJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Pixy2SpiJNI
 * Method:    pixy2SpiInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_frc_robot_vision_Pixy2SpiJNI_pixy2SpiInit(JNIEnv *, jobject);

/*
 * Class:     Pixy2SpiJNI
 * Method:    pixy2SpiGetVersion
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_frc_robot_vision_Pixy2SpiJNI_pixy2SpiGetVersion(JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_frc_robot_vision_Pixy2SpiJNI_pixy2SpiLampOn(JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_frc_robot_vision_Pixy2SpiJNI_pixy2SpiLampOff(JNIEnv *, jobject);

JNIEXPORT jstring JNICALL Java_frc_robot_vision_Pixy2SpiJNI_pixy2SpiGetBlocksString(JNIEnv *, jobject);

/*
 * Class:     Pixy2SpiJNI
 * Method:    pixy2SpiGetBlocks
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_frc_robot_vision_Pixy2SpiJNI_pixy2SpiGetBlocks(JNIEnv *, jobject);
 
#ifdef __cplusplus
}
#endif
#endif