/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TestRoboRioPixy2SPIJNI */
 
#ifndef _Included_TestRoboRioPixy2SPIJNI
#define _Included_TestRoboRioPixy2SPIJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TestRoboRioPixy2SPIJNI
 * Method:    pixy2SpiInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_frc_robot_TestRoboRioPixy2SPIJNI_pixy2SpiInit(JNIEnv *, jobject);

/*
 * Class:     TestRoboRioPixy2SPIJNI
 * Method:    pixy2SpiGetVersion
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_frc_robot_TestRoboRioPixy2SPIJNI_pixy2SpiGetVersion(JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_frc_robot_TestRoboRioPixy2SPIJNI_pixy2SpiLampOn(JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_frc_robot_TestRoboRioPixy2SPIJNI_pixy2SpiLampOff(JNIEnv *, jobject);

JNIEXPORT jstring JNICALL Java_frc_robot_TestRoboRioPixy2SPIJNI_pixy2SpiGetBlockString(JNIEnv *, jobject);

/*
 * Class:     TestRoboRioPixy2SPIJNI
 * Method:    pixy2SpiGetBlocks
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_frc_robot_TestRoboRioPixy2SPIJNI_pixy2SpiGetBlocks(JNIEnv *, jobject);
 
#ifdef __cplusplus
}
#endif
#endif